### ISSUE TITLE
static folder not included in the PyPI package

### ISSUE THREAD

**Issue by mchaaler** [smarie/mkdocs-gallery#19]
Something to do with the 'include_package_data' option in setup.cfg?
Would adopting a src layout be a solution?

- https://blog.ionelmc.ro/2014/05/25/python-packaging/
- https://hynek.me/articles/testing-packaging/

**Comment by smarie** [comment]
Fixed in 0.7.1 (with non-regression tests). Let me know if this works on your side !

**Comment by mchaaler** [comment]
Tested and approved (on a real-life project)! Thanks a lot!

**Comment by smarie** [comment]
great ! thanks for letting me know. I had planned to use it on https://python-qds.github.io/qdscreen/ but did not yet have the bandwidth, so you are officially the first (non-self) user project !
