### ISSUE TITLE
GalleryPlugin.on_page_content() crashing when page.edit_url is None

### ISSUE THREAD

**Issue by mchaaler** [smarie/mkdocs-gallery#32]
This happens when the "edit_uri" parameter is set to an empty string, as advised in [MkDocs documentation](https://www.mkdocs.org/user-guide/configuration/#edit_uri) when one does not want any "edit URL link" displayed on the documentation pages.

**Comment by smarie** [comment]
By the way, why did you want to disable the "edit uri" option ? Just being curious

**Comment by mchaaler** [comment]
> By the way, why did you want to disable the "edit uri" option ? Just being curious

At work we're hosting the project's documentation on an internal Apache web server, and I was not sure that the 'edit' link would work as expected.

Seems to me that the edit capability is tightly linked to the services provided by the hosting platform. For example, on Github, clicking on 'Edit this page' opens a page mentioning that "Submitting a change will write it to a new branch in your fork ...".

But if you have any idea on how to enable such editing capabilities in a simple way, that would certainly be useful for us! I must however confess I did not spend much time looking for additional details in MkDocs or Materials documentation pages.

**Comment by smarie** [comment]
Indeed 

> On a few known hosts (specifically GitHub, Bitbucket and GitLab), the edit_uri is derived from the 'repo_url' and does not need to be set manually. Simply defining a repo_url will automatically populate the edit_uri configs setting.

> To use a different URI than the default, simply set the edit_uri to your desired string.

Let me know when you try - I'd be interested to know if the modification of edit uri that I do on the gallery pages is compliant with this scenario :)

https://www.mkdocs.org/user-guide/configuration/#edit_uri
