### ISSUE TITLE
Failing tests when launched under WSL

### ISSUE THREAD

**Issue by mchaaler** [smarie/mkdocs-gallery#37]
Happened when trying to reproduce #34 on linux (WSL2 - Win11).

![image](https://user-images.githubusercontent.com/98430048/158889828-2bfad9b3-a9cf-41f4-ab25-7e861689ee0b.png)

Seems to be caused by the use of `session.run2("pip install [-e] . --no-deps")` in `noxfile.py`.
But I admit I don't know why it fails on a WSL install and not on a linux host such as those used for the build.

**Comment by smarie** [comment]
Fixed by #39
