### ISSUE TITLE
TypeError: startswith first arg must be str or a tuple of str, not WindowsPath

### ISSUE THREAD

**Issue by smarie** [smarie/mkdocs-gallery#45]
This happens when we use the `mkdocs serve` mode:

```
  File "C:\(...)\mkdocs_gallery\plugin.py", line 352, in _callback
    if event.src_path.startswith(g):
TypeError: startswith first arg must be str or a tuple of str, not WindowsPath
```

Probably related to the last changes with the pathlib paths everywhere.

**Comment by mchaaler** [comment]
Strange... I cannot reproduce the bug. 
Does it happen when working on mkdocs-gallery documentation itself?

**Comment by mchaaler** [comment]
> 



> Strange... I cannot reproduce the bug.
> Does it happen when working on mkdocs-gallery documentation itself?

Yes I do. One needs to modify an example file, of course... 🤦

**Comment by smarie** [comment]
Oops sorry, my issue description was not good enough, I should have stated the clear procedure for reproducing the issue..
