### ISSUE TITLE
mkdocs-gallery breaks mkdocstrings links in non-gallery pages

### ISSUE THREAD

**Issue by tlambert03** [smarie/mkdocs-gallery#73]
It appears that any mkdocstrings link that uses backticks for formatting like ``[`magicgui.some.class`][]`` breaks when mkdocs gallery is enabled, even if it's a file that has nothing to do with an example.   Here are some screenshots:

with mkdocs-gallery enabled:

<img width="705" alt="Screen Shot 2023-09-07 at 6 42 58 AM" src="https://github.com/pyapp-kit/magicgui/assets/1609449/6c7a338c-1757-42fb-b402-2f1e1cfe27c0">

without mkdocs-gallery enabled:

<img width="707" alt="Screen Shot 2023-09-07 at 6 43 32 AM" src="https://github.com/pyapp-kit/magicgui/assets/1609449/f59bb5e5-0c92-4f94-805a-0d65848ca3a0">

do you have any thoughts as to why mkdocs gallery might be affecting the behavior of other plugins even in non-gallery pages?

**Comment by tlambert03** [comment]
I was able to determine that this is caused by the addition of the `pymdownx.inlinehilite` extension to config['markdown_extensions'] [here](https://github.com/smarie/mkdocs-gallery/blob/89fea9eacf6b9742fdbe2622f7d6a7d525db42a9/src/mkdocs_gallery/plugin.py#L219).  I can reproduce it merely by adding that directly to my config (and excluding mkdocs-gallery altogether).  So, it's obviously not an issue here.  sorry for the noise!

**Comment by tlambert03** [comment]
cross-ref: https://github.com/mkdocstrings/autorefs/issues/34

**Comment by smarie** [comment]
THanks @tlambert03 for reporting and cross-referencing ! Definitely useful for our knowledge base.
