### ISSUE TITLE
Unstated requirement to name examples with "plot_<blah>"

### ISSUE THREAD

**Issue by Samreay** [smarie/mkdocs-gallery#74]
Hi @smarie, wondering if this is a documentation issue or a genuine bug.

I'm trying to get the examples working in my own project, but getting this:

![image](https://github.com/smarie/mkdocs-gallery/assets/6748505/66c90cb9-e2d9-46ed-8611-e73b3afe52f3)

It's copied/pasted from https://github.com/smarie/mkdocs-gallery/blob/main/docs/examples/plot_0_sin.py, but as you can see for some reason the code is never actually run (0.0000s execution time). Even if I add an `import time` and `time.sleep(1)` to be explicit, it still appears nothing is run.

Aaaand as I'm writing this I've figured it out.

Your files have to be prepended with "plot" for them to actually run. I dont think this is documented on the main page, it might be fun to document this on the main page

**Comment by smarie** [comment]
Hi @Samreay indeed good catch ! 

The explanation is here:
https://sphinx-gallery.github.io/stable/configuration.html#parsing-and-executing-examples-via-matching-patterns

Our current doc is not very explicit indeed : 

![image](https://github.com/smarie/mkdocs-gallery/assets/3236794/7bd93bf5-2eee-461d-8988-99006ba99e5c)

Do not hesitate to make a proposal with a pr !
