### ISSUE TITLE
distuitils Version classes are deprecated

### ISSUE THREAD

**Issue by Samreay** [smarie/mkdocs-gallery#76]
Hi @smarie!

Looks like a fairly simple change, but right now Im getting a ton of deprecation warnings:

```bash
generating gallery for /home/runner/work/ChainConsumer/ChainConsumer/docs/generated/gallery... :  80%|████████  | 4/5 [00:26<00:05,  5.45s/it]INFO    -  DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  File "/home/runner/work/ChainConsumer/ChainConsumer/.venv/lib/python3.10/site-packages/mkdocs_gallery/py_source_parser.py", line 109, in _get_docstring_and_rest
    if LooseVersion(sys.version) >= LooseVersion("3.7"):
  File "/home/runner/work/ChainConsumer/ChainConsumer/.venv/lib/python3.10/site-packages/setuptools/_distutils/version.py", line 55, in __init__
    warnings.warn(
```

Which boil down to:

`DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.`

Hopefully the fix is a simple swap here: https://github.com/smarie/mkdocs-gallery/blob/89fea9eacf6b9742fdbe2622f7d6a7d525db42a9/src/mkdocs_gallery/py_source_parser.py#L16

From

```python
from distutils.version import LooseVersion
```

to

```python
from packaging.version import Version
```

And then updating

```python
    if LooseVersion(sys.version) >= LooseVersion("3.7"):
```

I believe you could also make use of `from packaging.version import parse` if you wanted too.

**Comment by smarie** [comment]
Thanks @Samreay  ! Indeed this is the correct fix. Also there is a need to update the `install_requires` as shown here : https://github.com/smarie/python-pytest-cases/pull/312/files

Do you feel like opening a PR ?

**Comment by Samreay** [comment]
@smarie sure thing. Three new PRs now in your inbox awaiting your thoughts
